import { nanoid } from "nanoid";

export const Topic_list = [
    {
        id:nanoid(),title:'企業管理功能會受到那些影響?',answer:4,
        options:['利害關係人','企業環境','全部皆非','除全部皆非以外全部皆是']
    },
    {
        id:nanoid(),title:'以下何者不是管理資訊系統結構?',answer:1,
        options:['總經理室部門組織','管理資訊系統部門組織及作業程序','資訊管理的發展內容','企業應用系統(AP,application system)']
    },
    {
        id:nanoid(),title:'管理資訊系統的歷程包含哪些階段?',answer:3,
        options:['電子數據處理階段','管理資訊系統階段','全部皆是','決策支援系統階段']
    },
    {
        id:nanoid(),title:'管理資訊系統在企業營運層次的定位?',answer:4,
        options:['決策層次','現場操作層次','全部皆是','管理和作業程序']
    },
    {
        id:nanoid(),title:'企業營運流程主要是在控管甚麼?',answer:4,
        options:['全部皆非','資料','資訊','除全部皆非以外全部皆是']
    },
    {
        id:nanoid(),title:'整合性報表在MIS上可分成那些報表?',answer:4,
        options:['決策分析','模擬分析','全部皆是','作業程序']
    },
    {
        id:nanoid(),title:'下列何者不是資料特性的重點?',answer:3,
        options:['全部皆非','未經整理的','有用的','原始的']
    },
    {
        id:nanoid(),title:'人機互動之所以困難重重,主要原因在於?',answer:4,
        options:['以人為中心','使用者能在學習後很快地熟悉其他系統的操作','全部皆是','面對電腦的陌生感']
    },
    {
        id:nanoid(),title:'下列何者是資訊的特性重點?',answer:1,
        options:['有用的','原始的','未經整理','全部皆非']
    },{
        id:nanoid(),title:'其他系統是指管理資訊系統本身環境相關的支援性系統,主要包含?',answer:3,
        options:['會計系統','介面連接系統','全部皆是','採購系統']
    },
    {
        id:nanoid(),title:'MIS軟體包含哪些模組?',answer:4,
        options:['資料庫','企業邏輯功能','使用者介面','全部皆是']
    },
    {
        id:nanoid(),title:'從管理資訊系和其他系統關連的角度而言,企業若要整合及導入這些不同的系統,則在整合導入過程中,須考量哪三大因素?',answer:1,
        options:['全部皆是','資訊化顧問的輔導','MIS部門在企業的功效','軟體產品廠商的搭配']
    },
    {
        id:nanoid(),title:'協同產品是指?',answer:1,
        options:['CPC','ERP','CRM','全部皆是']
    },
    {
        id:nanoid(),title:'管理資訊系統是在企業管理層次的哪一層?',answer:2,
        options:['全部皆是','管理','策略','決策']
    },
    {
        id:nanoid(),title:'利用資訊管理的發展運作,設計建構出可應用在企業不同作業功能的資訊系統,是指?',answer:1,
        options:['企業應用系統','MIS作業程序','全部皆是','MIS組織']
    },
    {
        id:nanoid(),title:'管理資訊系統和作業系統關聯,他主要包含?',answer:2,
        options:['全部皆是','通訊','存取','檢核']
    },
    {
        id:nanoid(),title:'流程層面的效益?',answer:1,
        options:['全部皆是','流程自動化','改善再造','步驟合理化']
    },
    {
        id:nanoid(),title:'管理資訊系統和資料庫系統關聯,他主要包含?',answer:4,
        options:['檢核','轉換','存取','全部皆是']
    }
]